// Package enroll implements the one-time registration call to the
// enroll-agent Edge Function. It takes a short code (generated by the
// iOS app) and exchanges it for agent credentials.
package enroll

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"
)

type Options struct {
	Code       string
	ProjectRef string
}

type Result struct {
	HostID       string
	RefreshToken string
	ProjectRef   string
}

type response struct {
	HostID       string `json:"host_id"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ProjectRef   string `json:"project_ref"`
	Error        string `json:"error"`
}

func Run(opts Options) (*Result, error) {
	endpoint := fmt.Sprintf("https://%s.supabase.co/functions/v1/enroll-agent", opts.ProjectRef)

	body, err := json.Marshal(map[string]string{"code": opts.Code})
	if err != nil {
		return nil, fmt.Errorf("marshal request: %w", err)
	}

	req, err := http.NewRequest("POST", endpoint, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("POST enroll-agent: %w", err)
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	var parsed response
	if err := json.Unmarshal(raw, &parsed); err != nil {
		return nil, fmt.Errorf("parse response (status %d): %w", resp.StatusCode, err)
	}

	if resp.StatusCode != http.StatusOK {
		msg := parsed.Error
		if msg == "" {
			msg = fmt.Sprintf("status %d", resp.StatusCode)
		}
		return nil, fmt.Errorf("%s", msg)
	}

	return &Result{
		HostID:       parsed.HostID,
		RefreshToken: parsed.RefreshToken,
		ProjectRef:   parsed.ProjectRef,
	}, nil
}
